fix(deps): PG version sync
GaloyMoney/blink pull request #4609
Opened 2024-10-08 10:04 UTC by k3yss

This PR syncs the postgresql versions for the docker-compose files as per the current infrastructure/

2024-10-09 01:29 UTC, dolcalmi requested changes

2024-10-09 01:29 UTC, dolcalmi commented on quickstart/docker-compose.yml
quickstart is updated automatically, should not be update it in this PR

2024-10-16 08:16 UTC, k3yss commented
@dolcalmi Can you re-review?

2024-10-18 00:01 UTC, dolcalmi approved these changes

2024-10-18 00:01 UTC, merged